# Generated by Django 2.2.5 on 2019-09-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('age', models.IntegerField()),
                ('myjob', models.TextField(max_length=50)),
            ],
        ),
    ]
